version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=857848422201.dkr.ecr.ap-south-1.amazonaws.com/web
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t web:latest .
      - docker tag web:latest 857848422201.dkr.ecr.ap-south-1.amazonaws.com/web:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 857848422201.dkr.ecr.ap-south-1.amazonaws.com/web:latest
      - printf '[{"name":"api","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinations.json
      - cat imagedefinations.json
artifacts:
  files: imagedefinations.json
